"""add unique constraint to winery name

Revision ID: eab7ec2e2bdb
Revises: ff5ce473bcd2
Create Date: 2026-09-21 20:08:09.376495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab7ec2e2bdb'
down_revision = 'ff5ce473bcd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('wineries_name_key', 'wineries', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wineries_name_key', 'wineries', type_='unique')
    # ### end Alembic commands ###
